# Generated by Django 4.2.1 on 2023-05-18 22:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('comment', models.EmailField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CreateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='Default', max_length=100)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('file_type', models.CharField(default=None, max_length=10)),
                ('file_data_type', models.CharField(default=None, max_length=20)),
                ('file', models.FileField(upload_to='')),
                ('columns', models.CharField(default='default', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Created Models',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('joined_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SortedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='Default', max_length=100)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('file_type', models.CharField(default=None, max_length=10)),
                ('file_data_type', models.CharField(default=None, max_length=20)),
                ('sorted_file', models.FileField(upload_to='')),
                ('columns', models.CharField(default='default', max_length=1000)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='transfer_models.member')),
                ('from_file', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='transfer_models.createmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='createmodel',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='transfer_models.member'),
        ),
    ]
