# Generated by Django 4.2.2 on 2023-09-18 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('model_name', models.CharField(default='Default', max_length=100)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('file_type', models.CharField(default=None, max_length=10)),
                ('file_data_type', models.CharField(default='N/A', max_length=20)),
                ('columns', models.CharField(default='default', max_length=1000)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Created Data Models',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('img_name', models.CharField(default=None, max_length=255)),
                ('file_type', models.CharField(default=None, max_length=255)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Image Data Created',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SortedDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('model_name', models.CharField(default='Default', max_length=100)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('file_type', models.CharField(default=None, max_length=10)),
                ('file_data_type', models.CharField(default='N/A', max_length=20)),
                ('columns', models.CharField(default=None, max_length=1000)),
                ('converted_columns', models.CharField(default=None, max_length=1000)),
                ('removed_columns', models.CharField(default=None, max_length=1000)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_file', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='transfer_models.datamodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sortedmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sortedmodel',
            name='from_file',
        ),
        migrations.DeleteModel(
            name='CreateModel',
        ),
        migrations.DeleteModel(
            name='SortedModel',
        ),
    ]
