# Generated by Django 4.2.2 on 2023-09-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_models', '0002_datamodel_imagemodel_sorteddatamodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datamodel',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Data Models'},
        ),
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Image Data Models'},
        ),
        migrations.AlterModelOptions(
            name='sorteddatamodel',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Sorted Data Models'},
        ),
    ]
